# ----- Builder stage -----
FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
# RUN npm ci --omit=dev
RUN npm install

# Copy only source and public assets, not the whole folder
COPY src/ ./src
COPY public/ ./public
COPY tsconfig.json ./

# Create non-root user
RUN addgroup -S sd-copilot-group && adduser -S sd-copilot-user -G sd-copilot-group
USER sd-copilot-user
ENV NODE_ENV=production
ENV PORT=3000

# Container Port
EXPOSE 3000 

CMD ["npm", "run", "dev"]