apiVersion: v1
kind: Service
metadata:
  name: sd-copilot-service
  namespace: sd-copilot
spec:
  selector:
    app: sd-copilot
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP