import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as resumeService from "../services/resume.service";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const mcpServer = new McpServer({
  name: "sd-resume-analyze-mcp",
  version: "1.0.0",
});

const ResumeAnalyzeInput = z.object({
  resumeText: z
    .string()
    .min(20, "Please provide the full resume text, not just a short snippet."),
  email: z
    .string()
    .optional()
    .describe(
      "Optional email to associate with a Interactive Coach user."
    ),
  targetRole: z
    .string()
    .optional()
    .describe("Optional target role, e.g. 'Senior Backend Engineer'."),
  targetCompany: z
    .string()
    .optional()
    .describe("Optional target company, e.g. 'Google' or 'Stripe'."),
});

type ResumeAnalyzeInput = z.infer<typeof ResumeAnalyzeInput>;

mcpServer.registerTool(
  "resume_analyze",
  {
    description:
      "Analyze a resume for strengths, weaknesses, skills, and improved bullets. Use when the user pastes their resume and wants structured feedback.",
    inputSchema: ResumeAnalyzeInput,
  },
  async (input: ResumeAnalyzeInput) => {
    try {
      const { resumeText, email, targetRole, targetCompany } = input;

      const result = await resumeService.analyzeResumeFromText({
        text: resumeText,
        email,
        targetRole,
        targetCompany,
      });
      return {
        content: [
          {
            type: "json",
            json: result,
          },
        ] as any,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        content: [
          {
            type: "text",
            text: `Resume analysis failed: ${message}}`,
          },
        ],
        isError: true,
      };
    }
  }
);

const ResumeTailorInput = z.object({
  resumeText: z
    .string()
    .min(20, "Please provide the full resume text to tailor."),
  jobDescription: z
    .string()
    .min(20, "Please provide the full job description / posting text."),
  targetRole: z
    .string()
    .optional()
    .describe(
      "Optional target role label, e.g. 'Senior Lead Software Developer'."
    ),
  targetCompany: z
    .string()
    .optional()
    .describe("Optional target company, e.g. 'FinTech company in Austin'."),
});

type ResumeTailorInput = z.infer<typeof ResumeTailorInput>;
mcpServer.registerTool(
  "resume_tailor",
  {
    description:
      "Tailor a resume to a specific job description. Use when the user provides their resume and a job posting and wants an ATS-friendly rewrite.",
    inputSchema: ResumeTailorInput,
  },
  async (input: ResumeTailorInput) => {
    try {
      const { resumeText, jobDescription, targetRole, targetCompany } = input;

      const result = await resumeService.tailorResumeFromText({
        text: resumeText,
        jobDescription,
        targetRole,
        targetCompany,
      });

      return {
        content: [
          {
            type: "json",
            json: result,
          },
        ] as any,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        content: [
          {
            type: "text",
            text: `Resume tailoring failed: ${message}`,
          },
        ],
        isError: true,
      };
    }
  }
);

mcpServer.registerTool(
  "resume_tailor_plaintext",
  {
    description:
      "Tailor a resume to a specific job description and return a single ATS-ready plain text resume. Use this when the user wants a ready-to-paste final resume.",
    inputSchema: ResumeTailorInput,
  },
  async (input: ResumeTailorInput) => {
    try {
      const { resumeText, jobDescription, targetRole, targetCompany } = input;

      const result = await resumeService.tailorResumeFromText({
        text: resumeText,
        jobDescription,
        targetRole,
        targetCompany,
      });

      const fullText =
        result.fullResumeText ??
        "No fullResumeText generated by tailorResumeFromText.";

      return {
        content: [
          {
            type: "text",
            text: fullText,
          },
        ],
      };
    } catch (err) {
      const error = err as Error;
      return {
        content: [
          {
            type: "text",
            text: `Resume tailoring (plaintext) failed: ${
              error.message ?? String(err)
            }`,
          },
        ],
        isError: true,
      };
    }
  }
);

async function main() {
  const transport = new StdioServerTransport();
  await mcpServer.connect(transport);
}

main().catch((err) => {
  console.error("MCP server failed:", err);
  process.exit(1);
});
